# Generated by Django 3.1.6 on 2021-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%y/%m/%d'),
        ),
    ]
