# Generated by Django 3.1.6 on 2021-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_poll_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ses',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
