# Generated by Django 3.1.6 on 2021-03-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_poll_ses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='ses',
        ),
        migrations.CreateModel(
            name='Ses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ses', to='rating.poll')),
            ],
        ),
    ]
