# Generated by Django 3.1.6 on 2021-03-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210305_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ses',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rating.poll'),
        ),
    ]
