# Generated by Django 3.1.6 on 2021-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20210305_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ses',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
